version = 0.1
[default.deploy.parameters]
stack_name = "no-lib-vector-search"
resolve_s3 = true
s3_prefix = "no-lib-vector-search"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
